import { NextRequest, NextResponse } from 'next/server'
import { getSession } from '@/lib/auth'

// Force dynamic rendering - this route uses cookies or request.url
export const dynamic = 'force-dynamic'

export async function POST(request: NextRequest) {
  try {
    const session = await getSession()
    if (!session) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const body = await request.json()
    const { format, period, currency, timestamp } = body

    // Generate export data based on format
    const exportData = await generateExportData(format, period, currency, timestamp)
    
    // Set appropriate headers based on format
    const headers = getExportHeaders(format, period)
    
    return new NextResponse(exportData.content, {
      status: 200,
      headers
    })
  } catch (error) {
    console.error('Analytics Export API error:', error)
    return NextResponse.json(
      { error: 'Export failed' },
      { status: 500 }
    )
  }
}

async function generateExportData(format: string, period: string, currency: string, timestamp: string) {
  const reportDate = new Date(timestamp).toLocaleDateString()
  
  switch (format) {
    case 'pdf':
      return {
        content: await generatePDFReport(period, currency, reportDate),
        type: 'application/pdf'
      }
    
    case 'excel':
      return {
        content: generateExcelData(period, currency, reportDate),
        type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
      }
    
    case 'csv':
      return {
        content: generateCSVData(period, currency, reportDate),
        type: 'text/csv'
      }
    
    default:
      throw new Error('Unsupported export format')
  }
}

function getExportHeaders(format: string, period: string) {
  const filename = `analytics-${period}-${Date.now()}`
  
  const headers: Record<string, string> = {
    'Cache-Control': 'no-cache'
  }
  
  switch (format) {
    case 'pdf':
      headers['Content-Type'] = 'application/pdf'
      headers['Content-Disposition'] = `attachment; filename="${filename}.pdf"`
      break
    
    case 'excel':
      headers['Content-Type'] = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
      headers['Content-Disposition'] = `attachment; filename="${filename}.xlsx"`
      break
    
    case 'csv':
      headers['Content-Type'] = 'text/csv'
      headers['Content-Disposition'] = `attachment; filename="${filename}.csv"`
      break
  }
  
  return headers
}

async function generatePDFReport(period: string, currency: string, reportDate: string) {
  // For now, return a simple text-based report
  // In production, you would use a PDF library like puppeteer or react-pdf
  const report = `
HITA&CO ANALYTICS REPORT
========================

Report Period: ${getPeriodLabel(period)}
Currency: ${currency}
Generated: ${reportDate}

EXECUTIVE SUMMARY
-----------------
• Total Revenue: $87,900
• Total Orders: 630
• Average Order Value: $139.52
• Growth Rate: +18.5%

TOP PERFORMING CATEGORIES
--------------------------
1. Traditional Jewelry - $28,500 (204 orders)
2. Ethnic Wear - $22,100 (158 orders)
3. Home Decor - $15,600 (112 orders)
4. Accessories - $12,800 (92 orders)
5. Lifestyle - $8,900 (64 orders)

GEOGRAPHIC PERFORMANCE
----------------------
1. United States - $35,200 (252 orders, 189 customers)
2. Canada - $18,900 (135 orders, 98 customers)
3. United Kingdom - $15,600 (112 orders, 87 customers)
4. Australia - $12,100 (87 orders, 65 customers)
5. Germany - $8,800 (63 orders, 52 customers)

INVENTORY STATUS
----------------
• In Stock: 128 products (82.1%)
• Low Stock: 18 products (11.5%)
• Out of Stock: 10 products (6.4%)

RECOMMENDATIONS
---------------
• Consider expanding Traditional Jewelry inventory
• Focus marketing efforts on high-performing regions
• Address low stock alerts for critical products
• Optimize pricing strategy for better conversion

---
Report generated by Hita&Co Analytics System
  `
  
  return Buffer.from(report, 'utf-8')
}

function generateExcelData(period: string, currency: string, reportDate: string) {
  // This would generate actual Excel data in production
  // For now, return CSV-like data that Excel can open
  const data = `
"Hita&Co Analytics Report"
"Period","${getPeriodLabel(period)}"
"Currency","${currency}"
"Generated","${reportDate}"
""
"SALES SUMMARY"
"Metric","Value"
"Total Revenue","$87,900"
"Total Orders","630"
"Average Order Value","$139.52"
"Growth Rate","+18.5%"
""
"CATEGORY PERFORMANCE"
"Category","Revenue","Orders","Products"
"Traditional Jewelry","$28,500","204","45"
"Ethnic Wear","$22,100","158","38"
"Home Decor","$15,600","112","29"
"Accessories","$12,800","92","34"
"Lifestyle","$8,900","64","18"
""
"GEOGRAPHIC DATA"
"Country","Revenue","Orders","Customers"
"United States","$35,200","252","189"
"Canada","$18,900","135","98"
"United Kingdom","$15,600","112","87"
"Australia","$12,100","87","65"
"Germany","$8,800","63","52"
  `
  
  return Buffer.from(data, 'utf-8')
}

function generateCSVData(period: string, currency: string, reportDate: string) {
  const csvData = `Date,Revenue,Orders,Average Order Value
2024-01-01,4520,32,141.25
2024-01-02,3890,28,138.93
2024-01-03,5670,41,138.29
2024-01-04,4320,31,139.35
2024-01-05,6210,45,138.00
2024-01-06,5480,39,140.51
2024-01-07,4890,35,139.71

Category Performance
Category,Revenue,Orders,Products
Traditional Jewelry,28500,204,45
Ethnic Wear,22100,158,38
Home Decor,15600,112,29
Accessories,12800,92,34
Lifestyle,8900,64,18

Geographic Data
Country,Revenue,Orders,Customers
United States,35200,252,189
Canada,18900,135,98
United Kingdom,15600,112,87
Australia,12100,87,65
Germany,8800,63,52
`
  
  return Buffer.from(csvData, 'utf-8')
}

function getPeriodLabel(period: string) {
  switch (period) {
    case '7d': return 'Last 7 Days'
    case '30d': return 'Last 30 Days'
    case '90d': return 'Last 3 Months'
    case '1y': return 'Last Year'
    default: return 'Custom Period'
  }
}